/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

version = "1.3.1"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    java
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

dependencies {
    shadow(project(":utils"))
    shadow("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
    shadow("net.citizensnpcs:citizens-main:2.0.35-SNAPSHOT")
    //shadow("org.spigotmc:spigot:1.18.2-R0.1-SNAPSHOT")
    shadow("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.34")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.processResources {
    filesMatching("plugin.yml") {
        filter { line ->
            line.replace("\${project.version}", project.version.toString())
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}
